name: Build PixelExperience ROM

on:
  push:
    branches:
      - fourteen

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Install repo tool
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+x ~/.bin/repo
        echo 'export PATH="$HOME/.bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc

    - name: Initialize local repository
      run: |
        ~/.bin/repo init -u https://github.com/PixelExperience/manifest -b fourteen

    - name: Sync repository
      run: |
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Set up environment
      run: . build/envsetup.sh

    - name: Choose a target
      run: lunch aosp_$device-userdebug

    - name: Build the code
      run: mka bacon -j$(nproc --all)
